# Generated by Django 3.1.5 on 2021-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('M&F', 'Meat and Fish'), ('F&V', 'Fruits and Vegetables'), ('Cooking', 'Cooking'), ('Beverages', 'BEVERAGES'), ('H&C', 'Home and Cleaning'), ('Pest Control', 'Pest Control'), ('Ofc Prod', 'Office Products'), ('Bt Prod', 'Beauty Products'), ('Hea Prod', 'Health Products'), ('PetCare', 'Pet Care'), ('Home App', 'Home Appliances'), ('Babycare', 'Baby Care')], max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
