# Generated by Django 3.1.5 on 2021-02-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
