# Generated by Django 3.1.5 on 2021-02-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_remove_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M&F', 'Meat and Fish'), ('F&V', 'Fruits and Vegetables'), ('Cooking', 'Cooking'), ('Beverages', 'BEVERAGES'), ('H&C', 'Home and Cleaning'), ('Pest Control', 'Pest Control'), ('Ofc Prod', 'Office Products'), ('Bt Prod', 'Beauty Products'), ('Hea Prod', 'Health Products'), ('PetCare', 'Pet Care'), ('Home App', 'Home Appliances'), ('Babycare', 'Baby Care'), ('fashion', 'Fashion'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=20),
        ),
    ]
