# Generated by Django 3.1.5 on 2021-02-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210215_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.profile'),
            preserve_default=False,
        ),
    ]
