# Generated by Django 3.1.5 on 2021-02-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
